### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by craff** [anuragsoni/poll#14]
Such a library needs more tests and github actions to test each PR on all available platforms (the developer may not have access to the three platforms) .

**Comment by craff** [comment]
The test must verify the O(1) (amortized or not) for the basic operations on euch platform.

**Comment by anuragsoni** [comment]
I'm going to close this now as there are GitHub actions that run on each platform and at-least basic level of tests that notifications surface when they should. If/when this library evolves there will be more tests added.
